Repository Zjjc123/guipy, pull requests merged in 2022-08, with the labels that each got.

#2 Poetry Packaging
  .github/workflows/deploy.yml
  build.sh
  guipy/components/slider.py
  guipy/manager.py
  poetry.lock
  pyproject.toml
  setup.cfg
Labels: enhancement, action

#5 Using Sphinx for Documentation and adding GitHub Action for Publishing Docs
  .github/workflows/docs.yml
  .vscode/settings.json
  docs/Makefile
  docs/changelog.rst
  docs/conf.py
  docs/getting_started/installation.rst
  docs/getting_started/overview.rst
  docs/getting_started/starting.rst
  docs/index.rst
  docs/make.bat
  guipy/manager.py
  poetry.lock
  pyproject.toml
Labels: documentation

#8 Fixing Build Files Path
  .github/workflows/docs.yml
Labels: documentation, action

#10 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: project

#11 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: project

#12 Basic README
  README.md
  build-doc.bat
  docs/getting_started/starting.rst
  docs/imgs/slider.gif
Labels: documentation

#18 Auto format to black format on save
  .vscode/settings.json
Labels: enhancement

#17 Skip modules/functions that start with "_" in autoapi
  docs/conf.py
Labels: documentation, enhancement

#20 Text and plotter
  guipy/components/component.py
  guipy/components/plot.py
  guipy/components/slider.py
  guipy/components/textbox.py
  guipy/manager.py
  guipy/utils.py
  test/plot_test.py
  test/slider_test.py
  test/textbox_test.py
Labels: enhancement

#21 Documentation
  guipy/components/_component.py
  guipy/components/plot.py
  guipy/components/slider.py
  guipy/components/textbox.py
  guipy/manager.py
  guipy/utils.py
  tests/plot_test.py
  tests/slider_test.py
  tests/textbox_test.py
Labels: documentation

#22 Changelog - Preparing for Release 0.2.0
  docs/changelog.rst
Labels: documentation
